# Generated by Django 5.2.17 on 2026-09-03 04:15

import django.core.validators
import django.db.models.deletion
import meals.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_alter_unit_abbrev'),
        ('recipes', '0003_alter_recipestats_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visibility', models.CharField(choices=[('PRIVATE', 'Private'), ('SHARED', 'Shared with specific people'), ('PUBLIC', 'Everyone with an account')], db_index=True, default='PRIVATE', max_length=16)),
                ('is_system', models.BooleanField(db_index=True, default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('copied_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copies', to='meals.dish')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('shared_with', models.ManyToManyField(blank=True, related_name='shared_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='dishes', to='catalog.tag')),
            ],
            options={
                'verbose_name_plural': 'dishes',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DishComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servings', models.DecimalField(decimal_places=2, default=1, max_digits=6, validators=[meals.models.validate_positive_servings])),
                ('position', models.PositiveIntegerField(default=0)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='meals.dish')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dish_components', to='recipes.recipe')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='DishStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('is_favorite', models.BooleanField(default=False)),
                ('times_made', models.PositiveIntegerField(default=0)),
                ('last_made_at', models.DateTimeField(blank=True, null=True)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='meals.dish')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RecipeBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visibility', models.CharField(choices=[('PRIVATE', 'Private'), ('SHARED', 'Shared with specific people'), ('PUBLIC', 'Everyone with an account')], db_index=True, default='PRIVATE', max_length=16)),
                ('is_system', models.BooleanField(db_index=True, default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('default_ordering', models.CharField(choices=[('MANUAL', 'Manual order'), ('NAME', 'Name'), ('RATING', 'Rating'), ('TIME', 'Total time'), ('TIMES_MADE', 'Times made')], default='MANUAL', max_length=16)),
                ('copied_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copies', to='meals.recipebook')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('shared_with', models.ManyToManyField(blank=True, related_name='shared_%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RecipeBookEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(blank=True, max_length=100)),
                ('position', models.PositiveIntegerField(default=0)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='meals.recipebook')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_entries', to='recipes.recipe')),
            ],
            options={
                'ordering': ['section', 'position'],
            },
        ),
        migrations.AddConstraint(
            model_name='dish',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_system', True), ('owner__isnull', True)), models.Q(('is_system', False), ('owner__isnull', False)), _connector='OR'), name='meals_dish_owner_xor_system'),
        ),
        migrations.AddConstraint(
            model_name='dishcomponent',
            constraint=models.CheckConstraint(condition=models.Q(('servings__gt', 0)), name='meals_dishcomponent_servings_positive'),
        ),
        migrations.AddConstraint(
            model_name='dishstats',
            constraint=models.CheckConstraint(condition=models.Q(('rating__isnull', True), models.Q(('rating__gte', 1), ('rating__lte', 5)), _connector='OR'), name='meals_dishstats_rating_range'),
        ),
        migrations.AddConstraint(
            model_name='dishstats',
            constraint=models.UniqueConstraint(fields=('user', 'dish'), name='meals_dishstats_unique_user_dish'),
        ),
        migrations.AddConstraint(
            model_name='recipebook',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_system', True), ('owner__isnull', True)), models.Q(('is_system', False), ('owner__isnull', False)), _connector='OR'), name='meals_recipebook_owner_xor_system'),
        ),
        migrations.AddConstraint(
            model_name='recipebookentry',
            constraint=models.UniqueConstraint(fields=('book', 'recipe'), name='meals_recipebookentry_unique_book_recipe'),
        ),
    ]
