# Generated by Django 5.2.17 on 2026-09-17 06:54
#
# D53 (ARCHITECTURE.md): DishComponent.recipe becomes nullable so accounts.services.delete_user's
# PROTECT-clearing pre-pass can neutralize a bystander's component whose recipe belonged to the
# deleted account (SET_NULL + graceful degradation) instead of hard-refusing the whole-account
# delete. on_delete stays PROTECT — an ordinary single-recipe delete is unaffected.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
        ('recipes', '0003_alter_recipestats_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishcomponent',
            name='recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dish_components', to='recipes.recipe'),
        ),
    ]
