# Generated by Django 5.2.17 on 2026-08-26 15:20

import catalog.models
import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('kind', models.CharField(choices=[('CUISINE', 'Cuisine'), ('PROTEIN', 'Protein'), ('DIET', 'Diet'), ('FREEFORM', 'Freeform')], default='FREEFORM', max_length=8)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'ordering': ['kind', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('plural', models.CharField(blank=True, max_length=40)),
                ('abbrev', models.CharField(max_length=12)),
                ('dimension', models.CharField(choices=[('MASS', 'Mass'), ('VOLUME', 'Volume'), ('COUNT', 'Count')], db_index=True, max_length=6)),
                ('to_base_factor', models.DecimalField(decimal_places=10, max_digits=20, validators=[catalog.models.validate_positive_factor])),
                ('count_family', models.CharField(blank=True, default='', max_length=20)),
                ('is_system', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['dimension', 'to_base_factor'],
                'constraints': [models.CheckConstraint(condition=models.Q(('to_base_factor__gt', 0)), name='catalog_unit_to_base_factor_positive')],
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visibility', models.CharField(choices=[('PRIVATE', 'Private'), ('SHARED', 'Shared with specific people'), ('PUBLIC', 'Everyone with an account')], db_index=True, default='PRIVATE', max_length=16)),
                ('is_system', models.BooleanField(db_index=True, default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('density_g_per_ml', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, validators=[catalog.models.validate_positive_density])),
                ('is_staple', models.BooleanField(default=False)),
                ('copied_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copies', to='catalog.ingredient')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('shared_with', models.ManyToManyField(blank=True, related_name='shared_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='ingredients', to='catalog.tag')),
                ('default_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingredients', to='catalog.unit')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('is_system', True), ('owner__isnull', True)), models.Q(('is_system', False), ('owner__isnull', False)), _connector='OR'), name='catalog_ingredient_owner_xor_system'), models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('owner'), condition=models.Q(('owner__isnull', False)), name='catalog_ingredient_unique_owner_name_ci'), models.UniqueConstraint(django.db.models.functions.text.Lower('name'), condition=models.Q(('is_system', True)), name='catalog_ingredient_unique_system_name_ci'), models.CheckConstraint(condition=models.Q(('density_g_per_ml__isnull', True), ('density_g_per_ml__gt', 0), _connector='OR'), name='catalog_ingredient_density_positive')],
            },
        ),
    ]
