# Generated by Django 5.2.17 on 2026-08-26 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='abbrev',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
