# Generated by Django 5.2.17 on 2026-09-04 04:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_alter_unit_abbrev'),
        ('meals', '0001_initial'),
        ('planner', '0001_initial'),
        ('recipes', '0003_alter_recipestats_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visibility', models.CharField(choices=[('PRIVATE', 'Private'), ('SHARED', 'Shared with specific people'), ('PUBLIC', 'Everyone with an account')], db_index=True, default='PRIVATE', max_length=16)),
                ('is_system', models.BooleanField(db_index=True, default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('kind', models.CharField(choices=[('SHOPPING', 'Shopping list'), ('MEAL_PLAN', 'Meal plan'), ('MENU', 'Menu'), ('GENERIC', 'List')], db_index=True, default='GENERIC', max_length=16)),
                ('is_default_shopping_list', models.BooleanField(default=False)),
                ('copied_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copies', to='lists.list')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('shared_with', models.ManyToManyField(blank=True, related_name='shared_%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_checked', models.BooleanField(default=False)),
                ('text', models.CharField(blank=True, max_length=500)),
                ('quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('source', models.CharField(choices=[('MANUAL', 'Added by hand'), ('GENERATED', 'Generated from a meal plan')], db_index=True, default='MANUAL', max_length=16)),
                ('dish', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='meals.dish')),
                ('generated_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_items', to='planner.mealplan')),
                ('ingredient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.ingredient')),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='lists.list')),
                ('recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='recipes.recipe')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.unit')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.AddConstraint(
            model_name='list',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_system', True), ('owner__isnull', True)), models.Q(('is_system', False), ('owner__isnull', False)), _connector='OR'), name='lists_list_owner_xor_system'),
        ),
        migrations.AddConstraint(
            model_name='list',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default_shopping_list', True)), fields=('owner',), name='lists_list_one_default_shopping_per_owner'),
        ),
        migrations.AddConstraint(
            model_name='listitem',
            constraint=models.CheckConstraint(condition=models.Q(('text__gt', ''), ('recipe__isnull', False), ('dish__isnull', False), ('ingredient__isnull', False), _connector='OR'), name='lists_listitem_has_content'),
        ),
    ]
