# Generated by Django 5.2.17 on 2026-08-30 02:07

import django.core.validators
import django.db.models.deletion
import recipes.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_alter_unit_abbrev'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visibility', models.CharField(choices=[('PRIVATE', 'Private'), ('SHARED', 'Shared with specific people'), ('PUBLIC', 'Everyone with an account')], db_index=True, default='PRIVATE', max_length=16)),
                ('is_system', models.BooleanField(db_index=True, default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('instructions', models.TextField(blank=True)),
                ('yield_quantity', models.DecimalField(decimal_places=3, max_digits=10, validators=[recipes.models.validate_positive_yield])),
                ('prep_minutes', models.PositiveIntegerField(default=0)),
                ('cook_minutes', models.PositiveIntegerField(default=0)),
                ('role', models.CharField(choices=[('PROTEIN', 'Protein'), ('CARB', 'Carb'), ('VEGETABLE', 'Vegetable'), ('ONE_POT', 'One-pot'), ('SAUCE', 'Sauce'), ('DESSERT', 'Dessert'), ('SIDE', 'Side'), ('BREAKFAST', 'Breakfast'), ('OTHER', 'Other')], db_index=True, default='OTHER', max_length=16)),
                ('source_url', models.URLField(blank=True)),
                ('copied_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copies', to='recipes.recipe')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('shared_with', models.ManyToManyField(blank=True, related_name='shared_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='recipes', to='catalog.tag')),
                ('yield_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipe_yields', to='catalog.unit')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RecipeComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('position', models.PositiveIntegerField(default=0)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('ingredient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='used_in_components', to='catalog.ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='recipes.recipe')),
                ('sub_recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='used_in', to='recipes.recipe')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipe_components', to='catalog.unit')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='RecipeStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('is_favorite', models.BooleanField(default=False)),
                ('times_made', models.PositiveIntegerField(default=0)),
                ('last_made_at', models.DateTimeField(blank=True, null=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='recipes.recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_stats', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='recipe',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_system', True), ('owner__isnull', True)), models.Q(('is_system', False), ('owner__isnull', False)), _connector='OR'), name='recipes_recipe_owner_xor_system'),
        ),
        migrations.AddConstraint(
            model_name='recipe',
            constraint=models.CheckConstraint(condition=models.Q(('yield_quantity__gt', 0)), name='recipes_recipe_yield_positive'),
        ),
        migrations.AddConstraint(
            model_name='recipecomponent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('ingredient__isnull', False), ('sub_recipe__isnull', True)), models.Q(('ingredient__isnull', True), ('sub_recipe__isnull', False)), _connector='OR'), name='recipes_component_ingredient_xor_subrecipe'),
        ),
        migrations.AddConstraint(
            model_name='recipestats',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='recipes_recipestats_unique_user_recipe'),
        ),
        migrations.AddConstraint(
            model_name='recipestats',
            constraint=models.CheckConstraint(condition=models.Q(('rating__isnull', True), models.Q(('rating__gte', 1), ('rating__lte', 5)), _connector='OR'), name='recipes_recipestats_rating_range'),
        ),
    ]
