# Generated by Django 5.2.17 on 2026-09-17 06:54
#
# D53 (ARCHITECTURE.md): relax RecipeComponent's ingredient/sub_recipe CheckConstraint from
# "exactly one set" to "at most one set", so accounts.services.delete_user's PROTECT-clearing
# pre-pass can null both fields on a tombstoned (bystander) component instead of hard-refusing
# the whole-account delete. Every normal write path still only ever produces exactly-one rows —
# both-null only ever happens through that pre-pass.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_unit_abbrev'),
        ('recipes', '0003_alter_recipestats_user'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='recipecomponent',
            name='recipes_component_ingredient_xor_subrecipe',
        ),
        migrations.AddConstraint(
            model_name='recipecomponent',
            constraint=models.CheckConstraint(condition=models.Q(('ingredient__isnull', True), ('sub_recipe__isnull', True), _connector='OR'), name='recipes_component_ingredient_xor_subrecipe'),
        ),
    ]
