spring:
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:sqlite:plantoplate.db?journal_mode=WAL&busy_timeout=5000
    driver-class-name: org.sqlite.JDBC
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
