# Generated by Django 5.2.17 on 2026-09-06 04:25

import datetime
import django.core.validators
import django.db.models.deletion
import planner.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_unit_abbrev'),
        ('lists', '0001_initial'),
        ('meals', '0001_initial'),
        ('planner', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mealplan',
            name='days',
            field=models.PositiveSmallIntegerField(default=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mealplan',
            name='profile_snapshot',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='seed',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mealplan',
            name='shopping_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meal_plans', to='lists.list'),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='start_date',
            field=models.DateField(default=datetime.date(2026, 1, 1)),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='MealPlanProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_default', models.BooleanField(default=False)),
                ('days', models.PositiveSmallIntegerField(default=7, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('slots', models.JSONField(default=planner.models.default_slots, validators=[planner.models.validate_slots])),
                ('dish_template', models.CharField(choices=[('BALANCED', 'Balanced (protein, carb, vegetable)'), ('ONE_POT', 'One-pot'), ('MIX', 'Mix it up')], default='BALANCED', max_length=16)),
                ('source_scope', models.CharField(choices=[('MINE', 'Only my dishes'), ('SHARED', 'My dishes and dishes shared with me'), ('PUBLIC', 'My dishes, shared, and public dishes')], default='SHARED', max_length=16)),
                ('tag_limits', models.JSONField(blank=True, default=dict, validators=[planner.models.validate_tag_limits])),
                ('no_repeat_days', models.PositiveSmallIntegerField(default=14)),
                ('min_rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('favorites_only', models.BooleanField(default=False)),
                ('favorites_bias', models.DecimalField(decimal_places=2, default=Decimal('1.5'), max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('max_total_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('exclude_staples', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('excluded_ingredients', models.ManyToManyField(blank=True, related_name='excluded_by_profiles', to='catalog.ingredient')),
                ('excluded_tags', models.ManyToManyField(blank=True, related_name='excluded_by', to='catalog.tag')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planner_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='mealplan',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans', to='planner.mealplanprofile'),
        ),
        migrations.CreateModel(
            name='MealPlanEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_index', models.PositiveSmallIntegerField()),
                ('slot', models.CharField(choices=[('BREAKFAST', 'Breakfast'), ('LUNCH', 'Lunch'), ('DINNER', 'Dinner')], max_length=16)),
                ('is_locked', models.BooleanField(default=False)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('dish', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='meals.dish')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='planner.mealplan')),
            ],
            options={
                'ordering': ['day_index', 'slot'],
                'constraints': [models.UniqueConstraint(fields=('plan', 'day_index', 'slot'), name='planner_mealplanentry_unique_day_slot')],
            },
        ),
        migrations.AddConstraint(
            model_name='mealplanprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('owner',), name='planner_mealplanprofile_one_default_per_owner'),
        ),
        migrations.AddConstraint(
            model_name='mealplanprofile',
            constraint=models.CheckConstraint(condition=models.Q(('days__gte', 1), ('days__lte', 7)), name='planner_mealplanprofile_days_range'),
        ),
        migrations.AddConstraint(
            model_name='mealplanprofile',
            constraint=models.CheckConstraint(condition=models.Q(('min_rating__isnull', True), models.Q(('min_rating__gte', 1), ('min_rating__lte', 5)), _connector='OR'), name='planner_mealplanprofile_min_rating_range'),
        ),
        migrations.AddConstraint(
            model_name='mealplanprofile',
            constraint=models.CheckConstraint(condition=models.Q(('favorites_bias__gte', 0)), name='planner_mealplanprofile_favorites_bias_non_negative'),
        ),
    ]
