# Generated by Django 5.2.17 on 2026-09-06 13:29

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
        ('planner', '0002_mealplan_days_mealplan_profile_snapshot_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealplan',
            name='days',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)]),
        ),
        migrations.AddConstraint(
            model_name='mealplan',
            constraint=models.CheckConstraint(condition=models.Q(('days__gte', 1), ('days__lte', 7)), name='planner_mealplan_days_range'),
        ),
    ]
